databases:
  - name: widget_app_db
    databaseName: db_widget_app_production
    user: user_widget_app_production
    plan: free

services:
  - type: web
    name: widget_app_web
    rootDir: server
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    runtime: ruby
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: widget_app_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: widget_app_redis
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production

  - type: worker
    name: widget_app_sidekiq
    rootDir: server
    buildCommand: "bundle install"
    startCommand: "bundle exec sidekiq"
    plan: starter # worker does not allow free tier
    runtime: ruby
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: widget_app_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: widget_app_redis
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production

  - type: redis
    name: widget_app_redis
    plan: free
    ipAllowList: [] # only allow internal connections
